[workspace]
members = ["cellular-automata", "act-cpm-ui", "boids", "boids-ui"]
resolver = "2"

[workspace.lints.clippy]
pedantic = "warn"
cast_precision_loss = "allow"
cast_possible_truncation = "allow"
