[package]
name = "boids"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
euclid = "0.22.9"
rand = "0.8.5"
