name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cargo cache
      uses: Swatinem/rust-cache@v2
    - name: Build and upload
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: act-cpm-ui
        token: ${{ secrets.GITHUB_TOKEN }}
